jira:
  url: "https://jira.atlassian.com"
  username: "admin"
  password: "admin"

ai:
  base_url: "https://api.openai.com/v1"
  api_key: "sk-proj-1234567890"
  model: "gpt-3.5-turbo"
  temperature: 0.5

db:
  host: "localhost"
  port: 3306
  username: "root"
  password: "1001"
  database: "jira"

sync:
  interval: 10 # 单位 min

